const MILLISECONDS_IN_A_SECOND = 1000;

const SECONDS_IN_A_MINUTE = 60;

const MINUTES_IN_AN_HOUR = 60;

const HOURS_IN_A_DAY = 24;

export const MILLISECONDS_IN_A_DAY =
  HOURS_IN_A_DAY * MINUTES_IN_AN_HOUR * SECONDS_IN_A_MINUTE * MILLISECONDS_IN_A_SECOND;

export const MILLISECONDS_IN_A_MINUTE = MILLISECONDS_IN_A_SECOND * SECONDS_IN_A_MINUTE;
